name: dim-powerlaw
dependencies:
  - python=3.7
  - pip
  - pip:
    - git+https://github.com/wktown/brain-score.git@ridge
    - git+https://github.com/wktown/model-tools.git
    - git+https://github.com/wktown/candidate_models.git
    #- git+https://github.com/wktown/unsup_vvs.git #candidate-models has unsup vss as a dependency
    - git+https://github.com/alexsax/visual-prior.git
    #- git+https://github.com/BonnerLab/bonnerlab-brainscore #for object2vec benchmark (default majaj)
    - jupyterlab
    - seaborn
    - umap-learn
    - git+https://github.com/johnmarktaylor91/torchlens.git


variables:
#*if these files are created when the environment is created:
#brainio  candidate-models  models  model-tools  result-caching  torchhub
# - those folders are used by the variables below

  TORCH_HOME: "/data/shared/torch"
  #can do (but currently empty) TORCH_HOME: "/data/keaton/torchhub"
  RESULTCACHING_HOME: "/data/keaton/result-caching"
  MT_HOME: "/data/keaton/model-tools"
  #*don't use .cache: MT_HOME: "/data/shared/.cache/brainscore/model-tools"
  #export MT_HOME="/data/mbonner5/shared/brainscore/model-tools"
  BRAINIO_HOME: "/data/keaton/brainio"
  #could use (but use above and test the difference) "/data/shared/brainio/bonner-datasets"
  # - use /shared/brainio is using bonner libraries only?
  #export BRAINIO_HOME="/data/mbonner5/shared/brainio/bonner-datasets"
  CM_HOME: "/data/keaton/candidate-models"
  #export CM_HOME="/data/mbonner5/shared/brainscore/candidate-models"

#used for Bonner_libraries and such only:
  BONNER_DATASETS_CACHE: "/data/shared/datasets"
  BONNER_BRAINIO_CACHE: "/data/shared/brainio"
  BONNER_BRAINIO_CATALOG_IDENTIFIER: "bonner-datasets"
  BONNER_BRAINIO_CATALOG_CSV: "/home/wtownle1/bonner-datasets/catalog.csv"
  BONNER_BRAINIO_LOCATION_TYPE: "rsync"
  BONNER_BRAINIO_LOCATION: "cogsci-ml.win.ad.jhu.edu:/export/data2/shared/brainio/bonner-datasets"


#brainio_home might need a directory with majaj stimuli and/or data?
#imagnet will be downloaded accordingly (I think)

#/data/shared/datasets = no majaj, yes ilsvrc + imagenet21k, yes NSD
#/data/shared/.cache/brainscore/brainio = yes majaj, no imagenet(s), no NSD
# -> should work for eigenspectrum_encoding
# - same with /data/shared/brainio/brain-score
#data/shared/brainio/bonner-datasets = NSD only
